name: test_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.2.1
  shared_preferences: ^2.1.2
  intl: ^0.18.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  auto_route: ^7.4.0
  image_picker: ^0.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-100-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-200-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-300-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-400-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-500-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-700-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-800-Bold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-900-ExtraBold.ttf
          weight: 900

